# -*- encoding: utf-8 -*-
$:.push File.expand_path("../lib", __FILE__)
require "foreigner-matcher/version"

Gem::Specification.new do |s|
  s.name        = "foreigner-matcher"
  s.version     = Foreigner::Matcher::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Cameron Dykes"]
  s.email       = ["yellow5c@gmail.com"]
  s.homepage    = "https://github.com/yellow5/foreigner-matcher"
  s.summary     = %q{Rspec matcher for testing the presence of foreign keys generated by Foreigner}
  s.description = %q{Adds rspec matcher to verify the presence of foreign keys generated by Foreigner in a table schema}

  s.add_dependency "foreigner", "0.9.1"

  s.rubyforge_project = "foreigner-matcher"

  s.files         = `git ls-files`.split("\n")
  s.test_files    = `git ls-files -- {test,spec,features}/*`.split("\n")
  s.executables   = `git ls-files -- bin/*`.split("\n").map{ |f| File.basename(f) }
  s.require_paths = ["lib"]
end
